### ISSUE TITLE
[Bug] Failed to inspect array

### ISSUE THREAD

**Issue by shachar1lavi** [ofer1katz/ivbscript#3]
Example:
```
In [1]: Array(1,2,3,4)
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\ipykernel\kernelbase.py", line 543, in execute_request
    self.do_execute(
  File "c:\git\ivbscript\ivbscript\kernel.py", line 148, in do_execute
    output = self._handle_vbscript_command(code)
  File "c:\git\ivbscript\ivbscript\kernel.py", line 132, in _handle_vbscript_command
    output = json.loads(output_file.read())
  File "C:\Program Files (x86)\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ofer1katz** [comment]
should write `Array(1,2,3,4)?` to inspect
