### ISSUE TITLE
[Bug] Got an error when calling a specific function

### ISSUE THREAD

**Issue by shachar1lavi** [ofer1katz/ivbscript#6]
The scenario that raising the error:
```
In [1]: Function formatString(format, arguments)
      :     Dim stringBuilder: Set stringBuilder = CreateObject("System.Text.StringBuilder")
      :     Call stringBuilder.AppendFormat_4(format, (arguments))
      :     formatString = stringBuilder.ToString()
      :     stringBuilder.Length = 0
      :     Set stringBuilder = Nothing
      : End Function

In [2]: formatString("{0}:\{1}", Array("C", "Windows"))
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\ipykernel\kernelbase.py", line 543, in execute_request
    self.do_execute(
  File "c:\git\ivbscript\ivbscript\kernel.py", line 148, in do_execute
    output = self._handle_vbscript_command(code)
  File "c:\git\ivbscript\ivbscript\kernel.py", line 132, in _handle_vbscript_command
    output = json.loads(output_file.read())
  File "C:\Program Files (x86)\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Python38-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 1 column 41 (char 40)
```

**Comment by ofer1katz** [comment]
Fixed
